version: '3.10'

services:
  db_techno:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  django:
    container_name: techno
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/techno/manage.py makemigrations --noinput &&
      python /usr/src/techno/manage.py migrate --noinput &&
      python /usr/src/techno/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/techno
    ports:
      - 8000:8000
    depends_on:
      - db_techno
volumes:
  postgres_data:

