# Generated by Django 4.0.5 on 2022-06-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='audio_file',
            new_name='path',
        ),
        migrations.RemoveField(
            model_name='song',
            name='audio_link',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
