# Generated by Django 4.0.5 on 2022-06-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_title_song_name_rename_audio_file_song_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
